name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ppl-report

    strategy:
      matrix:
        node-version: [ 20.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Nowa wersja aplikacji do generowania raportów PPL jest dostępna. Możesz ją sprawdzić pod adresem: https://janjakubik.pl/"}' ${{secrets.PPL_SLACK_NOTIFICATION}}
      - run: |
          curl -X PATCH https://janjakubik.pl/git-reload --header "${{secrets.MAGIC_HEADER_NAME}}: ${{secrets.MAGIC_HEADER_VALUE}}"
      - name: Sleep for 120 seconds (VPS is cheap :) )
        uses: jakejarvis/wait-action@master
        with:
          time: '120s'
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Nowa wersja aplikacji do generowania raportów PPL jest dostępna (wersja ${{ steps.package-version.outputs.current-version}}). Możesz ją sprawdzić pod adresem: https://janjakubik.pl/"}' ${{secrets.PPL_SLACK_GENERAL}}
